apiVersion: v1
kind: Secret
metadata:
  name: {{ template "account.fullname" . }}
  labels:
    app: {{ template "account.name" . }}
    chart: {{ template "account.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  ConnectionStringsDefault: {{.Values.env.connectionStrings.default | trimAll "\"" | b64enc | quote}}